<?php

return [

    'items' => [
        [
            'type' => 'link',
            'label' => 'Dashboard',
            'route' => 'dashboard',
            'active_routes' => ['dashboard'],
            'icon' => 'home',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Profil PT',
            'route' => 'admin.profil-pt.index',
            'active_routes' => ['admin.profil-pt.*'],
            'icon' => 'building',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Data Mahasiswa',
            'route' => 'admin.mahasiswa.index',
            'active_routes' => ['admin.mahasiswa.*'],
            'icon' => 'users',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Kelas Perkuliahan',
            'route' => 'admin.kelas.index',
            'active_routes' => ['admin.kelas.*'],
            'icon' => 'academic',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Nilai Perkuliahan',
            'route' => 'admin.nilai.index',
            'active_routes' => ['admin.nilai.*'],
            'icon' => 'chart',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Data Dosen',
            'route' => 'admin.dosen.index',
            'active_routes' => ['admin.dosen.*'],
            'icon' => 'teacher',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Aktivitas Kuliah',
            'route' => 'admin.perkuliahan.index',
            'active_routes' => ['admin.perkuliahan.*'],
            'icon' => 'clipboard',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Konversi Nilai',
            'route' => 'admin.konversi-nilai.index',
            'active_routes' => ['admin.konversi-nilai.*'],
            'icon' => 'swap',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Mahasiswa Lulus/DO',
            'route' => 'admin.mahasiswa-keluar.index',
            'active_routes' => ['admin.mahasiswa-keluar.*'],
            'icon' => 'graduate',
            'roles' => ['*'],
        ],
        [
            'type' => 'link',
            'label' => 'Pengaturan Koneksi',
            'route' => 'admin.settings.index',
            'active_routes' => ['admin.settings.*'],
            'icon' => 'cog',
            'roles' => ['superadmin'],
        ],
        [
            'type' => 'link',
            'label' => 'Master Pengguna',
            'route' => 'admin.users.index',
            'active_routes' => ['admin.users.*'],
            'icon' => 'user-shield',
            'roles' => ['superadmin'],
        ],
        [
            'type' => 'link',
            'label' => 'Pemetaan Feeder',
            'route' => 'admin.mapping.index',
            'active_routes' => ['admin.mapping.*'],
            'icon' => 'map',
            'roles' => ['superadmin'],
        ],
    ],

];
